// Code generated by "stringer -type OrderSide"; DO NOT EDIT.

package robinhood

import "strconv"

const _OrderSide_name = "SellBuy"

var _OrderSide_index = [...]uint8{0, 4, 7}

func (i OrderSide) String() string {
	if i < 0 || i >= OrderSide(len(_OrderSide_index)-1) {
		return "OrderSide(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderSide_name[_OrderSide_index[i]:_OrderSide_index[i+1]]
}
