// Code generated by "stringer -type OptionDirection"; DO NOT EDIT.

package roho

import "strconv"

const _OptionDirection_name = "DebitCredit"

var _OptionDirection_index = [...]uint8{0, 5, 11}

func (i OptionDirection) String() string {
	if i < 0 || i >= OptionDirection(len(_OptionDirection_index)-1) {
		return "OptionDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OptionDirection_name[_OptionDirection_index[i]:_OptionDirection_index[i+1]]
}
