// Code generated by "stringer -type OrderType"; DO NOT EDIT.

package roho

import "strconv"

const _OrderType_name = "MarketLimit"

var _OrderType_index = [...]uint8{0, 6, 11}

func (i OrderType) String() string {
	if i < 0 || i >= OrderType(len(_OrderType_index)-1) {
		return "OrderType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderType_name[_OrderType_index[i]:_OrderType_index[i+1]]
}
